volumes:
  postgres_data:
    name: postgres_data

networks:
  prisma-network:
    name: prisma-network

services:
  db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  bot:
    container_name: agl-timetable-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    networks:
      - prisma-network
    depends_on:
      db:
        condition: service_healthy
